version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-ezgin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - mynetwork
  
  phpmyadmin:
    image: linuxserver/phpmyadmin
    container_name: my-phpmyadmin-ezgin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    restart: always
    networks:
      - mynetwork

  

  backend:
    build:
      context: ./backend
    container_name: my-backend-ezgin
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - mysql
    restart: always
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge

