[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "long hazard course alter gospel plate sense pool tiny myself tide mom october famous will leaf focus border meat clock noise okay someone dog"
