[project]
name = 'ChainGo'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
clarity_version = 3
epoch = 3.1

[contracts.token]
path = 'contracts/token.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
